# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation
---
# all, none, or list of linter keys
APPLY_FIXES: none
# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
ENABLE_LINTERS:
  - CPP_CLANG_FORMAT
  - YAML_V8R
  - YAML_YAMLLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - REPOSITORY_GIT_DIFF
SHOW_ELAPSED_TIME: true
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - .direnv
  - build
  - vendor
