repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: v9.4.0
    hooks:
      - id: megalinter-incremental
        stages:
          - pre-commit
      - id: megalinter-full
        stages:
          - pre-push
