#!/bin/sh -eu

PROGNAME="$(basename $0)"
BASEDIR="$(cd $(dirname $0); pwd)"
PROJDIR="$(cd $BASEDIR/..; pwd)"

CURRENT=$(git describe --abbrev=0)
COMMIT=yes

help() {
    cat <<EOF >&2
USAGE:
  $PROGNAME (major|minor|patch)
  $PROGNAME -h | --help

OPTIONS:
  -h, --help

ARGUMENTS:
  major
    Update the major version.

  minor
    Update the minor version.

  patch
    Update the patch version.
EOF
    exit 0
}

while [ $# -gt 0 ]
do
  case "$1" in
    '-h' | '--help')
      help
      ;;
    '--no-commit')
      COMMIT=no
      shift
      ;;
    'major' | 'minor' | 'patch')
      break
      ;;
    *)
      help
      ;;
  esac
done

VERSION=$(npx semver $CURRENT -i $1)

echo "Bumping the version to $VERSION..."
# Don't use the -i option of `sed`.
# The incompatibility between macOS and GNU will cause troubles.
sed -r -e "s|^set\(MIRAKC_ARIB_VERSION .*|set\(MIRAKC_ARIB_VERSION \"$VERSION\"|" \
  $PROJDIR/CMakeLists.txt | sponge $PROJDIR/CMakeLists.txt

# Make sure that cmake can generate project files successfully.
BUILD_DIR=$(mktemp -d)
trap "rm -rf $BUILD_DIR" EXIT
cmake -S . -B $BUILD_DIR -D CMAKE_BUILD_TYPE=Release

# TODO: Genereate CHANGELOG.md

if [ "$COMMIT" = yes ]
then
  git add $PROJDIR/CMakeLists.txt
  git commit -m "misc: bump version to $VERSION"

  echo "Making an annotated tag for $VERSION..."
  git tag -a "$VERSION" -m "release: $VERSION"
fi
