#!/bin/sh

PROGNAME="$(basename $0)"
BASEDIR="$(cd $(dirname $0); pwd)"
PROJDIR="$(cd $BASEDIR/..; pwd)"

BASE_URL='https://api.github.com/repos'

FMT_VERSION="$(curl -s $BASE_URL/fmtlib/fmt/releases/latest | jq -r '.tag_name')"
SPDLOG_VERSION="$(curl -s $BASE_URL/gabime/spdlog/releases/latest | jq -r '.tag_name')"

cat <<EOF
Latest Tags:
  fmtlib/fmt:
    $FMT_VERSION
  gabime/spdlog:
    $SPDLOG_VERSION
EOF

git -C "${PROJDIR}/vendor/fmt" checkout -q "${FMT_VERSION}"
git -C "${PROJDIR}/vendor/spdlog" checkout -q "${SPDLOG_VERSION}"
