#!/bin/sh

PROGNAME="$(basename $0)"
BASEDIR="$(cd $(dirname $0); pwd)"
PROJDIR="$(cd $BASEDIR/..; pwd)"

FMT_VERSION="$(gh api repos/fmtlib/fmt/releases/latest --jq '.tag_name')"
SPDLOG_VERSION="$(gh api repos/gabime/spdlog/releases/latest --jq '.tag_name')"

cat <<EOF
Latest Tags:
  fmtlib/fmt:
    $FMT_VERSION
  gabime/spdlog:
    $SPDLOG_VERSION
EOF

git -C "${PROJDIR}/vendor/fmt" checkout -q "${FMT_VERSION}"
git -C "${PROJDIR}/vendor/spdlog" checkout -q "${SPDLOG_VERSION}"
