#!/bin/sh -eu

PROGNAME="$(basename $0)"
BASEDIR="$(cd $(dirname $0); pwd)"
PROJDIR="$(cd $BASEDIR/..; pwd)"

LOG_MD_FILE="${1:-/dev/null}"

touch $LOG_MD_FILE

FMT_CURRENT=$(git -C "$PROJDIR/vendor/fmt" describe --tags)
FMT_VERSION="$(gh api repos/fmtlib/fmt/releases/latest --jq '.tag_name')"
if [ "$FMT_CURRENT" != "$FMT_VERSION" ]
then
  echo "- Bumps vendor/fmt from $FMT_CURRENT to $FMT_VERSION" | \
    tee -a $LOG_MD_FILE
  git -C "$PROJDIR/vendor/fmt" checkout -q "$FMT_VERSION"
fi

SPDLOG_CURRENT=$(git -C "$PROJDIR/vendor/spdlog" describe --tags)
SPDLOG_VERSION="$(gh api repos/gabime/spdlog/releases/latest --jq '.tag_name')"
if [ "$SPDLOG_CURRENT" != "$SPDLOG_VERSION" ]
then
  echo "- Bumps vendor/spdlog from $SPDLOG_CURRENT to $SPDLOG_VERSION" | \
    tee -a $LOG_MD_FILE
  git -C "$PROJDIR/vendor/spdlog" checkout -q "$SPDLOG_VERSION"
fi
