name: cross-build

on:
  workflow_call:

permissions: {}

jobs:
  cross-build:
    strategy:
      matrix:
        arch:
          - i686
          # Disabled because there is no linux/arm/v5 image of ubuntu.
          # - armel
          - armhf
          - arm64
        include:
          - arch: i686
            host-triple: i686-linux-gnu
            elf-machine: 'Intel 80386'
            elf-flags: '0x0'
            docker-platform: linux/386
          # - arch: armel
          #   host-triple: arm-linux-gnueabi
          #   elf-machine: 'ARM'
          #   elf-flags: 'soft-float'
          #   docker-platform: linux/arm/v5
          - arch: armhf
            host-triple: arm-linux-gnueabihf
            elf-machine: 'ARM'
            elf-flags: 'hard-float'
            docker-platform: linux/arm/v7
          - arch: arm64
            host-triple: aarch64-linux-gnu
            elf-machine: 'AArch64'
            elf-flags: ''
            docker-platform: linux/arm64/v8
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends autoconf automake cmake dos2unix g++-$HOST_TRIPLE libtool make ninja-build pkg-config
        env:
          HOST_TRIPLE: ${{ matrix.host-triple }}
      - name: Generate project files
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D MIRAKC_ARIB_TEST=ON -D CMAKE_TOOLCHAIN_FILE=toolchain.cmake.d/debian-$ARCH.cmake .
        env:
          ARCH: ${{ matrix.arch }}
      - name: Build vendor libraries
        run: |
          ninja -C build vendor
      - name: Build
        run: |
          ninja -C build
      - name: Check the binary format
        run: |
          readelf -h build/bin/mirakc-arib | grep Machine | grep "$ELF_MACHINE"
          readelf -h build/bin/mirakc-arib | grep Flags | grep "$ELF_FLAGS"
        env:
          ELF_MACHINE: ${{ matrix.elf-machine }}
          ELF_FLAGS: ${{ matrix.elf-flags }}
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Show help and version
        run: |
          docker run --rm -v $(pwd)/build:/build --platform $PLATFORM debian:stable-slim /build/bin/mirakc-arib -h
          docker run --rm -v $(pwd)/build:/build --platform $PLATFORM debian:stable-slim /build/bin/mirakc-arib --version
        env:
          PLATFORM: ${{ matrix.docker-platform }}
      - name: Run tests
        run: |
          docker run --rm -e CI=$CI -v $(pwd)/build:/build --platform $PLATFORM debian:stable-slim /build/bin/mirakc-arib-test --gtest_shuffle
          docker run --rm -e CI=$CI -v $(pwd)/build:/build -v $(pwd)/test:/test --platform $PLATFORM debian:stable-slim sh /test/cli_tests.sh /build/bin/mirakc-arib
        env:
          PLATFORM: ${{ matrix.docker-platform }}
