name: macos-build

on:
  workflow_call:

jobs:
  macos-build:
    runs-on: macos-latest
    continue-on-error: true  # macOS is unsupported officially
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Cache for external projects
        uses: actions/cache@v4
        with:
          path: build/vendor
          key: ${{ runner.os }}-macos-build-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-macos-build-
      - name: Install deps
        run: |
          brew install autoconf automake gnu-sed grep dos2unix libtool make ninja pkg-config
      - name: Generate project files
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D MIRAKC_ARIB_TEST=ON
      - name: Build vendor libraries
        run: |
          ninja -C build vendor
      - name: Build
        run: |
          ninja -C build
      - name: Show help and version
        run: |
          build/bin/mirakc-arib -h
          build/bin/mirakc-arib --version
      - name: Run tests
        run: |
          ninja -C build test
          ninja -C build cli-tests
