name: macos-build

on:
  workflow_call:

permissions: {}

jobs:
  macos-build:
    runs-on: macos-latest
    continue-on-error: true  # macOS is unsupported officially
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
      - name: Install deps
        run: |
          brew install autoconf automake gnu-sed grep dos2unix libtool make ninja pkg-config
      - name: Generate project files
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D MIRAKC_ARIB_TEST=ON
      - name: Build vendor libraries
        run: |
          ninja -C build vendor
      - name: Build
        run: |
          ninja -C build
      - name: Show help and version
        run: |
          build/bin/mirakc-arib -h
          build/bin/mirakc-arib --version
      - name: Run tests
        run: |
          ninja -C build test
          ninja -C build cli-tests
